# Legacy Makefile - use CMake instead
# Run: just p1::build

.PHONY: all build clean

all: build

build:
	@echo "Use 'just p1::build' to build the project"
	@just p1::build

clean:
	@echo "Use 'just p1::clean' to clean the project"
	@just p1::clean
